---
- hosts: localhost
  name: prometheus installation
  tasks:
    - name: Ensure Docker is installed if not install
      yum:
       name: docker
       state: latest
    - name: Start docker service, if not start
      service:
        name: docker
        enabled: yes
        state: started
    - name: Ensure python-Docker package is installed, if not install
      yum:
       name: python-docker
       state: latest
    - name: Prometheus container creation
      docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        detach: yes
        ports:
           - "9090:9090"
        volumes:
           - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - name: Copying Service file to /etc/systemd/system path to run prometheus as a systemd service
      copy:
        src: prometheus.service
        dest: /etc/systemd/system
        remote_src: no
        owner: root
        mode: 0777
    - name: Enable prometheus systemd service and ensure it is running
      service:
        name: prometheus.service
        enabled: yes
        state: started
    - name: Check if Prometheus is accessible
      uri:
        url: http://localhost:9090
        method: GET
        status_code: 200

        


