---
    - name: Ensure yum-utils present for adding docker repo
      yum:
       name: yum-utils
       state: present
    
    - name: add yum-config-manager for installing docker-ce
      shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  
    - name: install docker-ce
      yum:
       name:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - python-docker 
       state: present

    - name: Start docker service, if not start
      service:
        name: docker
        enabled: yes
        state: started
    - name: Get Kong IP
      shell: echo $(sudo kubectl get svc | grep kong | awk '{print $4}')
      register: kong_ip_addr
      delegate_to: "{{ groups['kube-masters'][0] }}"
    - name: Get Kong Port
      shell: |
            echo $(sudo kubectl get svc -n kong | grep kong | awk '{print $5}' | awk -F"/" '{print $1}' | awk -F":" '{print $2}')
      register: kong_node_port
      delegate_to: "{{ groups['kube-masters'][0] }}"

    - set_fact:
        kong_ip: "{{ kong_ip_addr.stdout }}"
    - set_fact:
        kong_port: "{{ kong_node_port.stdout }}"

    #- name: To check if prometheus host folder exists
     # stat:
      # path: "{{ prometheus_config_folder }}"
      #register: prometheus_config_folder_exists
    - name: Create prometheus host config folder
      file:
            path: "{{ prometheus_config_folder }}"
            state: directory
            mode: 0777
#            owner: 65534
 #           group: 65534
 
    - name: Copy prometheus config YAML file to the prometheus container
      template:
       src: prometheus.yml.j2
       dest: "{{ prometheus_config_folder }}/prometheus.yml"
       mode: 0777
      vars:
        kong_ip: "{{ kong_ip }}"
        kong_port: "{{ kong_port }}"        
 
    - name: Prometheus container creation
      docker_container:
        name: prometheus
        image: docker.io/prom/prometheus
        state: started
        detach: yes
        recreate: yes
        ports:
           - "{{ prometheus_port }}:9090"
        volumes:
           - "{{ prometheus_config_folder }}:/opt/prometheus/"
           
        command:
           - '--config.file=/opt/prometheus/prometheus.yml'
           #- '--storage.tsdb.path=/prometheus'
           #- '--web.console.libraries=/usr/share/prometheus/console_libraries'
           #- '--web.console.templates=/usr/share/prometheus/consoles'


    - name: Copying Service file to /etc/systemd/system path to run prometheus as a systemd service
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        remote_src: no
        owner: root
        mode: 0777
    - name: Enable prometheus systemd service and ensure it is running
      service:
        name: prometheus.service
        enabled: yes
        state: started
      ignore_errors: true
    - name: Check if Prometheus is accessible
      uri:
        url: http://localhost:9091
        method: GET
        status_code: 200
      ignore_errors: true
