#COnfigure worker node
- include_tasks: kubernetes_worker_prerequisites.yml

- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['kube-masters'][0] }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Run kubeadm join
  shell: "{{ kubeadm_join }}"
  #delegate_to: "{{ groups['kube-masters'][0] }}"
- pause:
    prompt: "Wait for containers to Pull and install"
