FROM rabbitmq:3.8.3-management

COPY rabbitmq.conf /etc/rabbitmq/
COPY custom_definitions.json /etc/rabbitmq/

RUN rabbitmq-plugins enable rabbitmq_management
RUN rabbitmq-plugins enable rabbitmq_peer_discovery_k8s
RUN rabbitmq-plugins enable rabbitmq_management_agent

CMD ["rabbitmq-server"]
