FROM arrun003/centos7java8:v1

LABEL maintainer "IClust Technologies"

RUN mkdir -p /app

COPY target/camel-consumer-0.0.1-SNAPSHOT.jar /app

WORKDIR /app

EXPOSE 8086

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "camel-consumer-0.0.1-SNAPSHOT.jar"]
