- name: "Stage 2: Initial DB"
  command: /usr/pgsql-{{postgresql_version}}/bin/postgresql-{{ postgresql_version |replace('.', '') }}-setup initdb
  when: installed.changed
  ignore_errors: True

- name: "Stage 2: configure postgresql.conf"
  template:
    src: postgresql.conf.j2
    dest: "/var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640

- name: "Stage 2: configure pg_hba.conf"
  template:
    src: pg_hba.conf.j2
    dest: "/var/lib/pgsql/{{ postgresql_version }}/data/pg_hba.conf"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640

- name: "Stage 3: Enabling the Service"
  systemd:
    name: postgresql-{{ postgresql_version |replace('.', '') }}
    enabled: yes

- name: "Stage 3: Starting the Service"
  systemd:
    name: postgresql-{{ postgresql_version |replace('.', '') }}
    state: restarted
