- name: "Stage 1: install repository package"
  yum: 
    state: present
    pkg: "{{ item.repo }}"
    validate_certs: no
  when: item.version == {{ postgresql_version }}
  with_items: "{{postgresql_repo_CentOS}}"

- name: "Stage 1: install postgresql packages"
  yum: 
    state: latest
    pkg: ["postgresql{{ postgresql_version |replace('.', '') }}-server", 'python-psycopg2']
  register: installed
  
- name: "Stage 1: install postgresql contrib package"
  yum: 
    state: latest
    pkg: postgresql{{ postgresql_version |replace('.', '') }}-contrib
  when: postgresql_contrib