- name: Configure Kube-adm master
  hosts: kube-masters
  become: true
  gather_facts: true
  vars:
    nodeip: var=ansible_eth0.ipv4.address
  roles:
    - kubeadm-master-role

- name: Configure Kube-adm worker
  hosts: kube-workers
  become: true
  gather_facts: true
  roles:
    - kubeadm-worker-role

- hosts: nfs-server
  gather_facts: yes
  become: yes
  roles:
   - name: Install NFS server
     role: nfs-role/server-nfs
     vars:
        nfs_exports:
          - path: "{{ nfs_server_export_dir }}"
            owner: root
            group: root
            mode: "0775"
            allow_from:
              - "{{ gvars_postgres_nfs_allowed_from_cidr }}"
- hosts: nfs-client
  gather_facts: yes
  become: yes
  roles:
   - name: Install NFS client software & create the fstab entry.
     role: nfs-role/client-nfs
     vars:
        nfs_client_remote_export: "{{ nfs_server_export_dir }}"
        nfs_client_share_mount_point: "{{ nfs_client_share_dir }}"
        nfs_host: "{{ hostvars[groups['nfs-server'][0]].ansible_eth0.ipv4.address }}"



- hosts: dbserver
  gather_facts: yes
  become: yes
  roles:
       - postgres
  vars:
     postgresql_allowed_cidr: "{{ gvars_postgres_nfs_allowed_from_cidr }}"


- name: Configure Kube-adm worker
  hosts: kube-masters
  become: true
  gather_facts: true
  roles:
    - rabbitmq-role
  vars: 
        ns_name: "{{ gvars_rabbitmq_namespace_name }}"

- hosts: kube-masters
  gather_facts: true
  become: true
  roles:
   - name: producer-app
     role: camel-apps
     vars:
        application_yml_file: "deployment-producer.yml"


- hosts: kube-masters
  gather_facts: true
  become: true
  roles:
   - name: consumer-app
     role: camel-apps
     vars:
        application_yml_file: "deployment-consumer.yml"
        postgres_ip: "{{ hostvars[groups['dbserver'][0]].ansible_eth0.ipv4.address }}"

- hosts: kube-masters
  gather_facts: true
  become: true
  roles:
    - istio

- hosts: kube-masters
  gather_facts: true
  become: true
  roles:
   - name: kong
     role: kong
     vars:
        kong_yml_file: "kong-dbless-istio.yml"

- hosts: kube-masters
  gather_facts: true
  become: true
  roles:
   - name: metallb-role
     role: metallb
     vars:
        metallb_ip_range: "{{ metallb_ip_range_list }}"
