- name: Configure Kube-adm master
  hosts: kube-masters
  become: true
  gather_facts: true
  vars:
    nodeip: var=ansible_eth0.ipv4.address
  roles:
    - kubeadm-master-role

- name: Configure Kube-adm worker
  hosts: kube-workers
  become: true
  gather_facts: true
  roles:
    - kubeadm-worker-role

- hosts: nfs-server
  gather_facts: yes
  become: yes
  roles:
   - name: Install NFS server
     role: nfs-role/server-nfs
     vars:
        nfs_exports:
          - path: "{{ nfs_server_export_dir }}"
            owner: root
            group: root
            mode: "0775"
            allow_from:
              - "{{ allowed_from_cidr }}"
- hosts: nfs-client
  gather_facts: yes
  become: yes
  roles:
   - name: Install NFS client software & create the fstab entry.
     role: nfs-role/client-nfs
     vars:
        nfs_client_remote_export: "{{ nfs_server_export_dir }}"
        nfs_client_share_mount_point: "{{ nfs_client_share_dir }}"
        nfs_host: "{{ hostvars[groups['nfs-server'][0]].ansible_eth0.ipv4.address }}"



- hosts: dbserver
  gather_facts: yes
  become: yes
  roles:
       - postgres


- name: Configure Kube-adm worker
  hosts: kube-masters
  become: true
  gather_facts: true
  roles:
    - rabbitmq-role

- hosts: kube-leader
  gather_facts: true
  become: true
  roles:
   - name: producer-app
     role: camel-apps
     vars:
        application_yml_file: "deployment-producer.yml"


- hosts: kube-leader
  gather_facts: true
  become: true
  roles:
   - name: consumer-app
     role: camel-apps
     vars:
        application_yml_file: "deployment-consumer.yml"
        postgres_ip: "{{ hostvars[groups['dbserver'][0]].ansible_eth0.ipv4.address }}"
