---

- hosts: kube-masters
  gather_facts: true
  become: true
  roles:
   - name: producer-app
     role: camel-apps
     vars_files:
        - group_vars/all.yml
     vars:
        application_yml_file: "deployment-producer.yml"
