apiVersion: v1
kind: Service
metadata:
  name: camel2-svc
spec:
  selector:
    app: camel2-consume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel2-consume
spec:
  selector:
    matchLabels:
      app: camel2-consume
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: camel2-consume
    spec:     # pod spec
      containers:
      - name: camel2-consume
        image: camelconsumerapp:latest
        imagePullPolicy: Never
