apiVersion: v1
kind: Service
metadata:
  name: camel-producer
  namespace: default
spec:
  sessionAffinity: None
  type: NodePort
  ports:
  - name: camel-producer-port
    port: 8085
    protocol: TCP
    targetPort: camel-producer
  selector:
    app: back-end
    type: camel-producer-jar

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-producer-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-end
      type: camel-producer-jar
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: back-end
        type: camel-producer-jar
      name: camel-producer
      namespace: default
    spec:
      containers:
      - image: akashbabu24/ascenthr:akash-clproducer
        imagePullPolicy: Always
        name: camel-producer-container
        env:
          - name: SPRING_APPLICATION_JSON
            value: '{
                "management.endpoints.web.exposure.include":"prometheus",
                "ascenthr.camel-rabbitmq-uri":"rabbitmq://rabbitmq.rabbitmq.svc.cluster.local:5672/example-exchange?vhost=example-vhost&queue=example-queue&username=admin&password=nimda&autoDelete=false&autoAck=true"
                }'
        ports:
        - containerPort: 8085
          name: camel-producer
          protocol: TCP
      restartPolicy: Always

      initContainers:
        - name: waiting-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup rabbitmq.rabbitmq.svc.cluster.local; do echo waiting for rabbitmq; sleep 2; done"]
