#Common Variable
epel_repo: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

#docker registry variables
nexus_docker_registry_url: 3.1.5.157:8082
nexus_docker_registry_user: admin
nexus_docker_registry_pwd: vine@2013
nexus_docker_registry_email: akashbabu24@iclust.com
if_insecure_registry: True

nfs_server_export_dir: /kubedata3
nfs_server_export_dir2: /postgresdata4
nfs_client_share_dir: /mnt/kubedata3
nfs_client_share_dir2: /mnt/postgresdata4
gvars_nfs_allowed_from_cidr: "*"            #for NFS server, the allowed CIDR to consume mounts. Other IP ranges would not be allowed to connect
gvars_postgres_allowed_from_cidr: 172.31.0.0/20  # for external postgres server, the allowed CIDR. Other IP ranges would not be allowed to connect

metallb_ip_range_list: ["172.31.14.1-172.31.14.10"]
gvars_rabbitmq_namespace_name: "rabbitmq"

#camel-apps variables

producer_docker_image_tag: akash-clproducer-metric
consumer_docker_image_tag: akash-clconsumer-metric
#producer_docker_image_tag: akash-clproducer-9d
#consumer_docker_image_tag: akash-clconsumer-17dnewdf


#kong
kong_domain: ec2-54-83-152-144.compute-1.amazonaws.com

#prometheus cars
gvars_prom_config_folder: /tmp/prom

#General ELK Settings
es_repo_base_url: https://artifacts.elastic.co/packages/7.x/yum
es_repo_gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

#ES Setting
es_local_port: 9200
es_listen_external: false
es_listen_address: "0.0.0.0"

#Kibana Settings
es_url: "http://localhost:9200"
kibana_user: admin
kibana_password: admin
www_kibana_port: 80
nginx_server_domain: 3.219.219.253     #Kibana browser-reachable IP to be added to Nginx config that is before Kibana. Private internal IP might not work if it is not reachable from browser as it is NGINX server 'domain/ip'.
#nginx_server_domain: "{{ groups['ELK'][0] }}"

#Logstash Setting
#
#
#Prometheus vars
prometheus_port: 9091
prometheus_config_folder: /tmp/prometheus
#Grafana vars
prometheus_ip: 3.219.219.253      #prometheus's browser-reachable IP for connection purposes from Grafana. Since Grafana is running as docker, ONLY browser-reachable IP works and not private server-internal IP.
grafana_config_folder: /tmp/grafana
grafana_port: 3000


#MongoDB
mongo_repo_base_url: https://repo.mongodb.org/yum/redhat/7Server/mongodb-org/4.4/x86_64/
mongo_repo_gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc

mongo_port: 27017
mongo_bind_ip: 0.0.0.0
mongo_user: admin
mongo_password: H5hP7YrO6q9c