nfs_server_export_dir: /kube-data
nfs_client_share_dir: /mnt/kube-data
gvars_postgres_nfs_allowed_from_cidr: 172.31.0.0/20

metallb_ip_range_list: ["172.31.14.1-172.31.14.10"]
gvars_rabbitmq_namespace_name: "rabbitmq"

#prometheus cars
gvars_prom_config_folder: /tmp/prom

#General ELK Settings
epel_repo: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
es_repo_base_url: https://artifacts.elastic.co/packages/7.x/yum
es_repo_gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

#ES Setting
es_local_port: 9200
es_listen_external: false
es_listen_address: "0.0.0.0"

#Kibana Settings
es_url: "http://localhost:9200"
kibana_user: admin
kibana_password: admin
www_kibana_port: 80
nginx_server_domain: 34.234.234.179
#nginx_server_domain: "{{ groups['ELK'][0] }}"

#Logstash Setting
