nfs_server_export_dir: /kube-data
nfs_client_share_dir: /mnt/kube-data
gvars_postgres_nfs_allowed_from_cidr: 172.31.0.0/20

metallb_ip_range_list: ["172.31.14.1-172.31.14.10"]
gvars_rabbitmq_namespace_name: "rabbitmq"
