apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-db
  labels:
    app: kong-db
spec:
  selector:
    matchLabels:
      app: kong-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/includeInboundPorts: "4242"
      labels:
        app: kong-db
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: kong-db
        image: kong
        imagePullPolicy: IfNotPresent
        env:
          - name: KONG_PG_HOST
            value: '172.31.3.11'
          - name: KONG_PG_USER
            value: 'ascentuser'
          - name: KONG_PG_PASSWORD
            value: 'ascent123' 
          - name: KONG_DATABASE
            value: 'db1'
          - name: KONG_PG_PORT
            value: 5432
          - name: KONG_LOG_LEVEL
            value: debug
          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_LISTEN
            value: '127.0.0.1:8001'
          - name: KONG_PROXY_LISTEN
            value: 0.0.0.0:8000,0.0.0.0:8443 ssl
          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001,0.0.0.0:8444 ssl
        ports:
        - name: admin-http
          containerPort: 8001
        - name: admin-http
          containerPort: 8444
        - name: data-http
          containerPort: 8000
        - name: data-https
          containerPort: 8443
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: kong-db
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
  - name: kong-admin-http
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: kong-admin-https
    port: 8444
    targetPort: 8444
    protocol: TCP
  - name: kong-proxy-http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-https
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: kong-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kongconfig
data:
  kong.yml: |
    _format_version: "1.1"
    services:
    - url: "http://mockbin.org/"
      routes:
      - paths:
        - "/mockbin"
    - url: "http://productpage.default.svc:9080"
      routes:
      - paths:
        - "/"
