---

- hosts: nfs-server
  gather_facts: yes
  become: yes
  roles: 
   - name: Install NFS server
     role: nfs-role/server-nfs
     vars:
        nfs_exports:
          - path: "{{ nfs_server_export_dir }}"
            owner: root
            group: root
            mode: "0775"
            allow_from:
              - "{{ allowed_from_cidr }}"
- hosts: nfs-client
  gather_facts: yes
  become: yes
  roles:
   - name: Install NFS client software & create the fstab entry.
     role: nfs-role/client-nfs
     vars:
        nfs_client_remote_export: "{{ nfs_server_export_dir }}"
        nfs_client_share_mount_point: "{{ nfs_client_share_dir }}"
        nfs_host: "{{ hostvars[groups['nfs-server'][0]].ansible_eth0.ipv4.address }}"
