---

- name: add the admin user
  mongodb_user: 
    database: "admin" 
    name: "{{ mongo_user }}" 
    password: "{{ mongo_password }}" 
    roles: readWriteAnyDatabase
    state: present
  no_log: true
  ignore_errors: yes
  notify:
    - restart mongod