---
- include_tasks: set_appropriate_cmd_path.yml
  when: cmd_path is not defined

- name: Extract server version
  shell: |
    {{ cmd_path }} version | sed -En "{{'s/Server Version.*GitVersion.*v([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+).*/\1/p'}}" | tail -1
  register: vo

#- assert:
 #   that:
  #    - "vo.stdout is version_compare(minimum_cluster_version,'>=')"
   # msg: "Cluster version must be at least {{ minimum_cluster_version }}"

- include_tasks: delete_resources.yml
  when: istio.delete_resources == true

- include_tasks: install_on_cluster.yml

#To enable istio injection in default workspace for all services to be attached an Envoy sidecar
- include_tasks: create_label.yml

