# Create a namespace if it doesn't exist
# The name of the namespace to create is given in variable ns_name

- name: Check if namespace for istio-system exists
  shell: "{{ cmd_path }} get namespace/{{ ns_name }}"
  ignore_errors: true
  register: if_namespace_present

- name: Create namespace {{ ns_name }}
  shell: "{{ cmd_path }} create namespace {{ ns_name }}"
  when:
    - if_namespace_present.stderr != ""
    - if_namespace_present.stderr.find("NotFound") != -1
