postgresql_version: 12
postgresql_contrib: yes

postgresql_allowed_cidr:

postgresql_repo_CentOS:
  - { version: "12", repo: "https://yum.postgresql.org/12/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm" }

postgresql_admin_user: "postgres"
postgresql_users:
 - { name: "ascentuser", pass: "ascent123", flags: "LOGIN,SUPERUSER" }

postgresql_encoding: UTF8
postgresql_locale: en_US.UTF-8
postgresql_databases:
 - { name: "ascentdb", owner: "ascentuser", template: "template0", encoding: "{{ postgresql_encoding }}", collate: "{{ postgresql_locale }}", ctype: "{{ postgresql_locale }}" }

postgresql_default_unix_auth_method: "trust"
postgresql_default_ipv4_auth_method: "md5"
postgresql_default_ipv6_auth_method: "md5"

postgresql_pg_hba_default:
 - { type: local, database: all, role: "{{ postgresql_admin_user }}", address: "", method: "{{ postgresql_default_unix_auth_method }}", comment: '"local" is for Unix domain socket connections only' }
 - { type: host, database: all, role: all, address: "0.0.0.0/0", method: "{{ postgresql_default_ipv4_auth_method }}", comment: 'IPv4 local connections:' }
 - { type: host, database: all, role: all, address: "::1/128", method: "{{ postgresql_default_ipv6_auth_method }}", comment: 'IPv6 local connections:' }

postgresql_pg_hba_custom:
 #- { type: host, database: all, role: all, address: "0.0.0.0/0", method: "{{ postgresql_default_ipv4_auth_method }}", comment: 'Allow All Connectios' }
 - { type: host, database: all, role: all, address: "{{ postgresql_allowed_cidr }}",  method: "{{ postgresql_default_ipv4_auth_method }}", comment: 'Allow All Connectios' }
