FROM arrun003/centos7java8:v1

LABEL maintainer "Arun Baskaran"

RUN mkdir -p /app

COPY target/camel-producer-0.0.1-SNAPSHOT.jar /app

WORKDIR /app

EXPOSE 8085

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "camel-producer-0.0.1-SNAPSHOT.jar"]
