
- name: To check if application_manifests folder exists
  stat:
    path: "{{ application_manifests }}"
  register: application_manifests_exists

- name: Create Application manifests folder
  shell: "mkdir {{ application_manifests }}"
  when:
     - not application_manifests_exists.stat.exists 

- name: Copy Producer app deployment YAML file to K8 master
  copy:
    src: "{{ application_yml_file }}"
    dest: "{{ application_manifests }}/{{ application_yml_file }}"
    mode: 0755
  when: application_yml_file == "deployment-producer.yml"

- name: Copy Consumer app deployment YAML file to K8 master
  template:
    src: deployment-consumer.yml.j2
    dest: "{{ application_manifests }}/deployment-consumer.yml"
    owner: root
    group: root
    mode: 0755
  when: application_yml_file == "deployment-consumer.yml"
  
- name: Deploy Application from kubernetes file
  shell: "{{ cmd_path }} create -f {{ application_manifests }}/{{ application_yml_file }}"
  ignore_errors: true

