
- name: To check if kong_manifests folder exists
  stat:
    path: "{{ kong_manifests }}"
  register: kong_manifests_exists

- name: Create Kong manifests folder
  shell: "mkdir {{ kong_manifests }}"
  when:
     - not kong_manifests_exists.stat.exists 

- name: Copy kong YAML file to K8 master
  template:
    src: "{{ item }}.j2"
    dest: "{{ kong_manifests }}/{{ item }}"
    mode: 0755
  with_items:
   - kong-namespace.yml
   - pv_postgres.yml 
   - pvc_postgres.yml
   - kong-database.yml

- name: Deploy Kong from kubernetes files
  shell: "{{ cmd_path }} apply -f {{ kong_manifests }}/kong-namespace.yml"
  ignore_errors: true

- name: Create label for kong with istio-injection enabled
  shell: "kubectl label namespace kong istio-injection=enabled"
  ignore_errors: true
- name: Deploy Kong from kubernetes files
  shell: "{{ cmd_path }} apply -f {{ kong_manifests }}/pv_postgres.yml -f {{ kong_manifests }}/pvc_postgres.yml -f {{ kong_manifests }}/kong-database.yml"
  ignore_errors: true

- include_tasks: configure_kong_ingress.yml
