- name: Upgrade all packages
  yum: name=* state=latest

- name: Install Docker
  package:
        name: docker
        state: latest
  become: yes

- name: Copy daemon.json for docker insecure registries
  template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0544'
  when: if_insecure-registry

- name: Start Docker service
  service:
        name: docker
        state: started
        enabled: yes
  become: yes
- name: Disable SELinux
  selinux:
        state: disabled
  register: selinux_state

- name: Register is_selinux_changed variable
  set_fact:
        selinux_changed: selinux_state.changed

- name: Reboot the machine
  reboot:
  when: selinux_changed

- name: Copy /etc/yum.repos.d/kubernetes.repo
  copy:
        src: files/kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo
        owner: root
        group: root
        mode: '0644'
- name: Upgrade all packages
  yum: name=* state=latest
- name: Install Kubernetes Package
  yum:
        name: "{{packages}}"
        state: present
  vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl
- name: Enable / Start kubelet Service
  service:
        name: kubelet
        state: started
        enabled: yes
- name: Letting iptables see bridged traffic
  copy:
        src: files/k8s.conf
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: '0644'
- name: Reload sysctl config for iptables
  command: sysctl --system
- name: Disable SWAP
  command: swapoff -a
