---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Create the share directory
  file:
    state: directory
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: 0755
    recurse: true
  with_items:
    - "{{ nfs_exports }}"

- name: Copy exports file to implement NFS exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: restart nfs-server

- name: Ensure nfs is running.
  service: 
      name: "{{ nfs_server_daemon }}"
      state: "{{ nfs_server_state }}"
      enabled: "{{ nfs_server_enabled }}"
  when: nfs_exports|length and nfs_service_managed

- name: Set threadcount for nfsd in sysconfig file.
  lineinfile:
      state: present
      insertafter: "^#RPCNFSDCOUNT=16"
      create: no
      regexp: '^RPCNFSDCOUNT=".*"'
      line: 'RPCNFSDCOUNT="{{ nfsd_threads }}"'
      dest: '/etc/sysconfig/nfs'
      backup: yes
  when: nfs_exports|length and nfs_service_managed and ansible_os_family == "RedHat"
  notify: 
    - restart nfs-config on EL7
    - restart nfs-server
