
- name: To check if MetalLB manifests folder exists
  stat:
    path: "{{ application_manifests }}"
  register: application_manifests_exists

- name: Create MetalLB  manifests folder
  shell: "mkdir {{ application_manifests }}"
  when:
     - not application_manifests_exists.stat.exists 

#- name: simulation of enabling strictARP for kube-proxy
 # shell: "{{ cmd_path }} get configmap kube-proxy -n kube-system -o yaml | sed -e \"s/strictARP: false/strictARP: true/\" | sudo {{ cmd_path }} diff -f - -n kube-system"

- name: Enabling strictARP for kube-proxy
  shell: "{{ cmd_path }} get configmap kube-proxy -n kube-system -o yaml | sed -e \"s/strictARP: false/strictARP: true/\" | sudo {{ cmd_path }} apply -f - -n kube-system"


- name: Copy metalLB YAML files to K8 master
  template:
    src: metallb.yml.j2
    dest: "{{ application_manifests }}/metallb.yml"
    owner: root
    group: root
    mode: 0755

- name: Copy metalLB YAML files to K8 master
  template:
    src: metallb-config.yml.j2
    dest: "{{ application_manifests }}/metallb-config.yml"
    owner: root
    group: root
    mode: 0755

- name: Deploy MetalLB from kubernetes file
  shell: "{{ cmd_path }} apply -f {{ application_manifests }}/metallb.yml -f {{ application_manifests }}/metallb-config.yml"
  ignore_errors: true

- name: Kubernetes Apps | Check existing secret of MetalLB
  command: "{{ cmd_path }} --kubeconfig /etc/kubernetes/admin.conf -n metallb-system get secret memberlist"
  register: metallb_secret
  become: true
  ignore_errors: yes
  when:
    - inventory_hostname == groups['kube-masters'][0]

- name: Kubernetes Apps | Create random bytes for MetalLB
  command: "openssl rand -base64 32"
  register: metallb_rand
  when:
    - inventory_hostname == groups['kube-masters'][0]
    - metallb_secret.rc != 0

- name: Kubernetes Apps | Install secret of MetalLB if not existing
  command: "{{ cmd_path }} --kubeconfig /etc/kubernetes/admin.conf -n metallb-system create secret generic memberlist --from-literal=secretkey={{ metallb_rand.stdout }}"
  become: true
  when:
    - inventory_hostname == groups['kube-masters'][0]
    - metallb_secret.rc != 0
