apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmq-0
  namespace: rabbitmq
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
       storage: 500Mi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmq-1
  namespace: rabbitmq
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
       storage: 500Mi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmq-2
  namespace: rabbitmq
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
       storage: 500Mi
