---
- name: Include distribution-specific variables
  include_vars: "{{ version_specific_vars_file }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"   # e.g. RedHat-6.yml, RedHat-7.yml
        - "{{ ansible_os_family }}.yml"                                            # e.g. RedHat.yml
      skip: true
  loop_control:
    loop_var: version_specific_vars_file

- name: Install packages
  include_tasks: "tasks/{{ ansible_os_family }}.yml"

- name: Check if mount point exists for NFS client
  stat:
    path: "{{ nfs_client_share_mount_point }}"
  register: stat_share_dir
  when: nfs_client_create_fstab_entry == true

- name: create share directory on client if not existing
  file:
      path: "{{ nfs_client_share_mount_point }}"
      state: directory
      mode: "u=rwx,g=rwx,o=rwx"
  when: stat_share_dir.stat.exists == false

- name: Create fstab entry for NFS client
  mount:
    name: "{{ nfs_client_share_mount_point }}"
    src: "{{ nfs_host }}:{{ nfs_client_remote_export }}"
    fstype: nfs
    opts: "{{ nfs_client_mount_opts }}"
    state: mounted
  when: nfs_client_create_fstab_entry == true

