apiVersion: v1
kind: Service
metadata:
  name: camel1-svc
spec:
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: camel1-produce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel1-produce
spec:
  selector:
    matchLabels:
      app: camel1-produce
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: camel1-produce
    spec:     # pod spec
      containers:
      - name: camel1-producer
        image: camelproducerapp:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8085
