FROM alpine-java:base
COPY target/camel-consumer-0.0.1-SNAPSHOT.jar /tmp
ENV SPRING_APPLICATION_JSON= '{ \
	"spring.datasource.url":"jdbc:postgresql://localhost:5432/ascenthr?currentSchema=ascenthr", \
	"spring.datasource.username":"postgres", \
	"spring.datasource.password":"postgres", \
  	"ascenthr.camel-rabbitmq-uri":"rabbitmq://localhost:5672/ascenthr.exchange?queue=employee.queue&username=full_access&password=admin&autoDelete=false&autoAck=true" \
  }'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/tmp/camel-consumer-0.0.1-SNAPSHOT.jar"]